### ISSUE TITLE
Types break for controlled field that has apostrophe

### ISSUE THREAD

**Issue by ekasprzyk** [intercom/contentful-typescript-codegen#74] opened 2021-03-29 11:01 UTC
e.g.

```
/** Guide type */
> 460 | type?: 'Biography' | 'Concise Introduction' | 'Director's Notebook' | 'Essay' | 'Graphic Novel' | 'Guide' | 'Play Text' | 'Revision Guide' | 'Study Guide' | undefined;
```

**Comment by lorcan** [comment] 2021-04-01 11:52
This looks like a duplicate of https://github.com/intercom/contentful-typescript-codegen/issues/34. I'm going to close this in favour of that issue.

**Closed by lorcan** 2021-04-01 11:52 UTC
